###
GET http://localhost:9090/produto

###
GET http://localhost:9090/produto/002

###
POST http://localhost:9090/produto
Content-Type: application/json

{
    "codigo": "001",
    "nome": "Heineken",
    "valor": 4.2
}

###
PUT http://localhost:9090/produto
Content-Type: application/json

{
    "codigo": "001",
    "nome": "Coca",
    "valor": 3.10
}

###
DELETE http://localhost:9090/produto/001