###
GET http://localhost:9090/produto

###
GET http://localhost:9090/produto/002

###
POST http://localhost:9090/produto
Content-Type: application/json

{
    "codigo": "005",
    "nome": "Agua de melao",
    "valor": 4.2
}

###
PUT http://localhost:9090/produto
Content-Type: application/json

{
    "codigo": "005",
    "nome": "Caipirinha azul",
    "valor": 2.5
}

###
DELETE http://localhost:9090/produto/delete/100